parameters:

    less_php.compiler.class: CSS\Bundle\LessPHPBundle\Compiler
    
services:
  
    less_php_compiler:
        class: %less_php.compiler.class%
        
    lessc:
        alias:  less_php_compiler